services:
  - type: web
    name: speech-intel-api
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 600
    envVars:
      - key: GROQ_API_KEY
        sync: false
    pythonVersion: 3.10.13